# Generated by Django 4.2.5 on 2024-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(max_length=1000, verbose_name='User Input Text')),
                ('sentiment', models.CharField(choices=[('HAPPY', 'Happy'), ('SAD', 'Sad')], default='HAPPY', max_length=10, verbose_name='Predicted Sentiment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
